-- AlterTable
ALTER TABLE `Service` MODIFY `category` ENUM('OFFICER_SERVICE', 'TAX_SERVICE', 'DELIVERY', 'WAREHOUSE_SERVICE', 'GOVERNMENT_SERVICE', 'GOVERNMENT_VAT', 'ETC') NOT NULL DEFAULT 'WAREHOUSE_SERVICE';
